#!/bin/sh

normal_dir="$1"
target_unit="${1}/eos-extra-settled.target"

unit="[Unit]
Description=endless-extra SD card mounted (if expected)
Wants=local-fs.target"

if [ -L "/etc/systemd/system/local-fs.target.wants/var-endless\x2dextra.mount" ]; then
  unit="${unit}\nRequiresMountsFor=/var/endless-extra"
fi

echo "${unit}" >"${target_unit}"
