#!/usr/bin/env python3

# Copyright © 2023 Endless OS Foundation, LLC
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or (at
# your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA
# 02110-1301, USA.

"""\
EOS EFI System Partition (ESP) mount generator

This program is responsible for mounting the EFI System Partition (ESP)
on EOS systems. It's heavily inspired by systemd-gpt-auto-generator with
a few policy changes that are not easily expressed there:

* Both GPT and MBR partition tables are supported.

* The EFI LoaderDevicePartUUID variable is validated but not required.
  This allows for usage with bootloaders such as GRUB that do not
  implement the boot loader interface.

* Mounting at /boot is allowed even when the /efi directory exists. This
  allows use of a generic OS commit that can be used on systems where
  /boot data exists in the ESP or not.

* When the ESP is mounted at /boot, it is made world readable to allow
  unprivileged ostree admin operations to succeed.

The units created with this generator take precedence over
systemd-gpt-auto-generator.
"""

from argparse import ArgumentParser, RawDescriptionHelpFormatter
from dataclasses import dataclass
import json
import logging
import os
from pathlib import Path
import shlex
import subprocess
import sys
from systemd.journal import JournalHandler
from textwrap import dedent

progname = os.path.basename(__file__)
logger = logging.getLogger(progname)

ESP_GPT_PARTTYPE = 'c12a7328-f81f-11d2-ba4b-00a0c93ec93b'
ESP_MBR_PARTTYPE = 'ef'
XBOOTLDR_GPT_PARTTYPE = 'bc13c2ff-59e6-4262-a352-b275fd6f7172'
LOADER_EFI_VENDOR = '4a67b082-0a4c-41cf-b6c7-440b29bb8c4f'
LOADER_DEVICE_PART_UUID_NAME = 'LoaderDevicePartUUID'
LOADER_DEVICE_PART_UUID_EFIVAR = f'{LOADER_DEVICE_PART_UUID_NAME}-{LOADER_EFI_VENDOR}'


class EspError(Exception):
    """ESP generator errors"""
    pass


def run(cmd, *args, **kwargs):
    """Run a command with logging"""
    logger.debug(f'> {shlex.join(cmd)}')
    return subprocess.run(cmd, *args, **kwargs)


def get_mount_data(root=Path('/')):
    """Gather mounted filesystems

    Returns a list of mounted filesystem dicts.
    """
    # If /boot or /efi are automounts, trigger the real mounts on
    # top of them. An access test is enough to trigger the mounts.
    # The directories should be kept open until mountinfo parsing
    # completes, but this should be good enough.
    root.joinpath('boot').exists()
    root.joinpath('efi').exists()

    cmd = (
        'findmnt',
        '--real',
        '--json',
        '--list',
        '--canonicalize',
        '--evaluate',
        '--nofsroot',
        '--output',
        'TARGET,SOURCE,MAJ:MIN,FSTYPE,FSROOT,OPTIONS',
    )

    opts = {
        'check': True,
        'stdout': subprocess.PIPE,
        'text': True,
        'encoding': 'utf-8',
    }

    proc = run(cmd, **opts)
    data = json.loads(proc.stdout).get('filesystems', {})
    logger.debug(f'mounts: {data}')
    return data


def get_fstab_data():
    """Gather filesystem mount configuration

    Returns a list of fstab entry dicts.
    """
    cmd = (
        'findmnt',
        '--fstab',
        '--json',
        '--list',
        '--canonicalize',
        '--evaluate',
        '--nofsroot',
        '--output',
        'TARGET,SOURCE,MAJ:MIN,FSTYPE,FSROOT,OPTIONS',
    )

    opts = {
        'check': True,
        'stdout': subprocess.PIPE,
        'text': True,
        'encoding': 'utf-8',
    }

    proc = run(cmd, **opts)
    data = json.loads(proc.stdout).get('filesystems', {})
    logger.debug(f'fstab: {data}')
    return data


def _disk_to_partitions(disk):
    """Convert sfdisk JSON to partition entries"""
    table = disk['partitiontable']
    for part in table['partitions']:
        # Lower case the partition type and UUIDs (if present) to
        # normalize later comparisons.
        part['type'] = part['type'].lower()
        if 'uuid' in part:
            part['uuid'] = part['uuid'].lower()
        part.update({
            'disk_node': table['device'],
            'disk_label': table['label'],
            'disk_id': table['id'].lower(),
        })
        yield part


def get_partition_data():
    """Gather disk partition data

    Returns a list of partition dicts.
    """
    partitions = []

    # Find the block devices that have partitions.
    sys_block = Path('/sys/block')
    for block in sys_block.iterdir():
        # If none of the sysfs device subdirs have partition entries,
        # then the block device doesn't have partitions.
        if not next(block.glob('*/partition'), None):
            continue

        disk_dev = f'/dev/{block.name}'
        cmd = (
            'sfdisk',
            '--json',
            disk_dev,
        )

        opts = {
            'check': True,
            'stdout': subprocess.PIPE,
            'text': True,
            'encoding': 'utf-8',
        }

        proc = run(cmd, **opts)
        disk_data = json.loads(proc.stdout)
        partitions += _disk_to_partitions(disk_data)

    logger.debug(f'partitions: {partitions}')
    return partitions


def read_efivar(name, root=Path('/')):
    """Read an EFI variable value

    Reads the data from efivarfs mounted at /sys/firmware/efi/efivars.
    Only the variable value is returned, not the attributes.
    """
    varpath = root / 'sys/firmware/efi/efivars' / name
    logger.debug(f'Reading EFI variable {varpath}')
    try:
        with open(varpath, 'rb') as f:
            value = f.read()
    except FileNotFoundError:
        logger.debug(f'EFI variable {name} not set')
        return None

    # Skip the first 4 bytes, those are the 32 bit attribute mask.
    if len(value) < 4:
        logger.warning(f'Invalid EFI variable {name} is less than 4 bytes')
        return None
    return value[4:]


def read_efivar_utf16_string(name, root=Path('/')):
    """Read an EFI variable UTF-16 string

    If the EFI variable doesn't exist, None is returned. Any nul
    terminating bytes will be removed.
    """
    value = read_efivar(name, root)
    if value is None:
        return None

    logger.debug(f'EFI variable {name} contents: {value}')

    # Systemd appends 3 nul bytes for some reason. If there are an odd
    # number of bytes, ignore the last one so there are an appropriate
    # number of utf16 bytes.
    end = len(value)
    if end % 2 == 1:
        end -= 1

    # Ignore any trailing nul byte pairs.
    while end > 0:
        if value[end - 2:end] != b'\0\0':
            break
        end -= 2

    return value[:end].decode('utf-16', errors='replace')


def systemd_escape_path(path):
    """Escape a path for usage in systemd unit names"""
    proc = run(
        ('systemd-escape', '--path', str(path)),
        check=True,
        stdout=subprocess.PIPE,
        text=True,
        encoding='utf-8',
    )
    return proc.stdout.strip()


@dataclass
class EspMount:
    """ESP mount specification

    Describes the parameters for mounting the ESP. The write_units()
    method can be used to create the systemd units from a generator.
    """
    source: str
    target: str
    type: str = 'vfat'
    umask: str = '0077'

    def write_units(self, unit_dir):
        source_escaped = systemd_escape_path(self.source)
        target_escaped = systemd_escape_path(self.target)
        automount_unit = unit_dir / f'{target_escaped}.automount'
        mount_unit = unit_dir / f'{target_escaped}.mount'
        local_fs_wants = unit_dir / 'local-fs.target.wants' / automount_unit.name

        logger.info(f'Writing unit {automount_unit}')
        automount_unit.write_text(dedent(f"""\
        # Automatically generated by {progname}

        [Unit]
        Description=EFI System Partition Automount

        [Automount]
        Where={self.target}
        TimeoutIdleSec=2min
        """))

        logger.info(f'Writing unit {mount_unit}')
        mount_unit.write_text(dedent(f"""\
        # Automatically generated by {progname}

        [Unit]
        Description=EFI System Partition Automount
        Requires=systemd-fsck@{source_escaped}.service
        After=systemd-fsck@{source_escaped}.service
        After=blockdev@{source_escaped}.target

        [Mount]
        What={self.source}
        Where={self.target}
        Type={self.type}
        Options=umask={self.umask},noauto,rw
        """))

        # Create a symlink for the automount unit in local-fs.target.wants.
        logger.info(f'Creating {local_fs_wants} symlink')
        local_fs_wants.parent.mkdir(parents=True, exist_ok=True)
        link = os.path.relpath(automount_unit, local_fs_wants.parent)
        os.symlink(link, local_fs_wants)


class EspGenerator:
    """Generator for mounting the ESP

    Locates the ESP device and determines the path to mount it at. Call
    get_esp_mount() to retrieve an EspMount instance describing the
    configuration.

    Note that the root parameter is used inconsistently. It is only
    intended for testing and should not be used in normal operation.
    """
    def __init__(self, root=Path('/')):
        self.root = root
        self.mounts = get_mount_data(self.root)
        self.fstab = get_fstab_data()
        self.partitions = get_partition_data()

    def get_esp_mount(self):
        """Get the ESP mount specification

        Returns an EspMount or None.
        """
        # Don't mount units in the initrd.
        if os.getenv('SYSTEMD_IN_INITRD', '0') == '1':
            logger.info('Skipping ESP mounting in initrd')
            return None

        esp_dev = self._get_esp_dev()
        if not esp_dev:
            logger.info('No ESP device found, skipping mounting')
            return None
        logger.info(f'ESP device: {esp_dev}')

        esp_path = self._get_esp_path(esp_dev)
        if not esp_path:
            logger.info('No ESP mount path determined, skipping mounting')
            return None
        logger.info(f'ESP mount path: {esp_path}')

        # If the desired path is in fstab, don't do anything.
        fstab_entry = self._get_fstab(target=esp_path)
        if fstab_entry:
            logger.info(
                f'{fstab_entry["source"]} configured for mounting at {esp_path}, '
                'skipping mounting'
            )
            return None

        # If the ESP is mounted at /boot, it needs to be world readable
        # since it's also accessed by ostree and some operations are
        # expected to work unprivileged.
        umask = '0022' if esp_path == '/boot' else '0077'

        mount = EspMount(source=esp_dev, target=esp_path, umask=umask)
        logger.info(f'Created ESP mount instance {mount}')
        return mount

    def _get_esp_dev(self):
        # FIXME: This only considers the partitions on the root
        # filesystem disk, but that's wrong in the dual boot case.
        esp_disk_part = self._get_root_partition()
        esp_disk_pttype = esp_disk_part['disk_label']
        esp_disk_parts = self._get_disk_partitions(esp_disk_part)

        esp_dev_part = {}
        if esp_disk_pttype == 'gpt':
            esp_dev_part = self._get_partition(
                esp_disk_parts,
                type=ESP_GPT_PARTTYPE,
            )
            if not esp_dev_part:
                logger.debug(
                    f'No GPT partition with ESP type {ESP_GPT_PARTTYPE} found '
                    f'in {esp_disk_parts}'
                )
                return None

            # Validate LoaderDevicePartUUID if it's set.
            loader_part_uuid = read_efivar_utf16_string(
                LOADER_DEVICE_PART_UUID_EFIVAR,
                self.root,
            )
            if loader_part_uuid is not None:
                loader_part_uuid = loader_part_uuid.lower()
                logger.debug(
                    f'Found EFI var {LOADER_DEVICE_PART_UUID_NAME} is '
                    f'{loader_part_uuid}'
                )
                esp_dev_uuid = esp_dev_part['uuid']
                if loader_part_uuid != esp_dev_uuid:
                    logger.info(
                        f'EFI variable {LOADER_DEVICE_PART_UUID_NAME} '
                        f'{loader_part_uuid} does not match located ESP UUID '
                        f'{esp_dev_part["uuid"]}'
                    )
                    return None
            else:
                logger.debug(f'EFI var {LOADER_DEVICE_PART_UUID_NAME} not set')
        elif esp_disk_pttype == 'dos':
            esp_dev_part = self._get_partition(
                esp_disk_parts,
                type=ESP_MBR_PARTTYPE,
            )
            if not esp_dev_part:
                logger.debug(
                    f'No MBR partition with ESP type {ESP_MBR_PARTTYPE} found '
                    f'in {esp_disk_parts}'
                )
        else:
            logger.warning(
                f'Unexpected partition type "{esp_disk_pttype}" for '
                f'{esp_disk_part["disk_node"]}'
            )

        return esp_dev_part.get('node')

    def _get_esp_path(self, esp_dev):
        has_xbootldr = self._root_has_xbootldr()
        has_efi_path = self.root.joinpath('efi').exists()

        def _use_efi_if_exists():
            if not has_efi_path:
                logger.info('Would use /efi for mount path, but it does not exist')
                return None
            return '/efi'

        if has_xbootldr:
            logger.debug('ESP device has XBOOTLDR partition, using /efi as mount path')
            return _use_efi_if_exists()

        boot_mount = self._get_mount(target='/boot')
        if boot_mount:
            if boot_mount['source'] == esp_dev:
                logger.debug(
                    f'Using /boot for mount path since {esp_dev} already mounted there'
                )
                return '/boot'
            else:
                logger.debug(
                    f'{boot_mount["source"]} is mounted at /boot, '
                    'using /efi as mount path'
                )
                return _use_efi_if_exists()
        else:
            boot_fstab = self._get_fstab(target='/boot')
            if boot_fstab and boot_fstab['source'] != esp_dev:
                logger.debug(
                    f'/boot is in fstab using {boot_fstab["source"]}, '
                    f'using /efi as mount path'
                )
                return _use_efi_if_exists()
            return '/boot'

        return None

    def _get_root_partition(self):
        root_mount = self._get_mount(target='/')
        if not root_mount:
            raise EspError(f'Could not find / mount in {self.mounts}')
        root_dev = root_mount['source']
        root_part = self._get_partition(node=root_dev)
        if not root_part:
            raise EspError(f'Could not find / device {root_dev} in {self.partitions}')
        logger.debug(f'Determined root partition {root_part}')
        return root_part

    def _get_disk_partitions(self, partition):
        return self._filter_data(self.partitions, disk_node=partition['disk_node'])

    def _root_has_xbootldr(self):
        root_part = self._get_root_partition()
        root_disk_parts = self._get_disk_partitions(root_part)
        xbootldr_part = self._get_partition(
            root_disk_parts,
            disk_label='gpt',
            type=XBOOTLDR_GPT_PARTTYPE,
        )
        return bool(xbootldr_part)

    @staticmethod
    def _filter_data(data, **kwargs):
        if not kwargs:
            raise ValueError('Must provide filter values')

        def _test(entry):
            for name, value in kwargs.items():
                if entry[name] != value:
                    return False
            return True

        return filter(_test, data)

    def _get_mount(self, data=None, **kwargs):
        if data is None:
            data = self.mounts
        return next(self._filter_data(data, **kwargs), {})

    def _get_fstab(self, data=None, **kwargs):
        if data is None:
            data = self.fstab
        return next(self._filter_data(data, **kwargs), {})

    def _get_partition(self, data=None, **kwargs):
        if data is None:
            data = self.partitions
        return next(self._filter_data(data, **kwargs), {})


def main():
    """ESP generator main entry point"""
    doclines = __doc__.splitlines()
    ap = ArgumentParser(
        description=doclines[0],
        epilog='\n'.join(doclines[2:]),
        formatter_class=RawDescriptionHelpFormatter,
    )
    ap.add_argument(
        'normal_dir',
        metavar='NORMAL',
        help='Normal generator output directory',
    )
    ap.add_argument(
        'early_dir',
        metavar='EARLY',
        help='Early generator output directory',
    )
    ap.add_argument(
        'late_dir',
        metavar='LATE',
        help='Late generator output directory',
    )
    ap.add_argument(
        '-n',
        '--dry-run',
        action='store_true',
        help='only show what would be done',
    )
    ap.set_defaults(log_level=logging.INFO)
    log_level_group = ap.add_mutually_exclusive_group()
    log_level_group.add_argument(
        '--quiet',
        dest='log_level',
        action='store_const',
        const=logging.WARNING,
        help='only log warning messages',
    )
    log_level_group.add_argument(
        '--debug',
        dest='log_level',
        action='store_const',
        const=logging.DEBUG,
        help='log debug messages',
    )
    args = ap.parse_args()

    # Setup logging. If we're run by systemd (SYSTEMD_SCOPE is set when
    # generators run), only use a journal handler.
    journal_handler = JournalHandler(SYSLOG_IDENTIFIER=progname)
    journal_handler.setFormatter(logging.Formatter(fmt='%(name)s:%(message)s'))
    handlers = [journal_handler]
    if 'SYSTEMD_SCOPE' in os.environ:
        # Tweak the logger name since the program name is superfluous in
        # the journal.
        logger.name = 'main'

        # For now just use debug level in systemd. Later we can try to
        # use the systemd log level for the program log level.
        args.log_level = logging.DEBUG
    else:
        # Add a stderr logger like would normally be done by
        # basicConfig.
        handlers.append(logging.StreamHandler(sys.stderr))
    logging.basicConfig(level=args.log_level, handlers=handlers)

    generator = EspGenerator()
    esp_mount = generator.get_esp_mount()
    if esp_mount and not args.dry_run:
        # The normal generator directory is used so that we take
        # precedence over systemd-gpt-auto-generator. However, this is
        # the same level as systemd-fstab-generator, so we need to take
        # care to not override fstab entries.
        unit_dir = Path(args.normal_dir)
        esp_mount.write_units(unit_dir)


if __name__ == '__main__':
    main()
