#!/bin/bash
# Copyright (C) 2018 Endless Mobile, Inc.
# Licensed under the GPLv2

if [ $# -lt 1 ] || [ "$1" -lt 0 ] || [ "$1" -gt 1 ]; then
	echo "Error: 0 or 1 must be specified" >&2
	exit 1
fi

ram_size_kb=$(awk '/MemTotal/{print $2}' /proc/meminfo)

if [ "$1" -ne 0 ]; then
    set -e
    if [ ! -e /sys/block/zram0 ]; then
        modprobe zram
    fi
    echo $((ram_size_kb * 3 / 2))K > /sys/block/zram0/disksize
    udevadm settle
    # For now, disable the swap partition if in use
    swapoff -a
    mkswap /dev/zram0
    swapon -d /dev/zram0
else
    swapoff /dev/zram0
    echo 1 > /sys/block/zram0/reset
fi
