#!/bin/bash -e

# eos-test-mode - Setup system for non-persistent testing.
# Copyright (C) 2015  Dan Nicholson <nicholson@endlessm.com>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# Check to see if we've run eos-live-boot-overlayfs-setup already
[ -d /run/eos-live ] && exit 0

# Mount overlays over any directory that might be written to
eos-live-boot-overlayfs-setup etc

# Disable the updater for this boot
systemctl mask --runtime --now eos-autoupdater.timer eos-autoupdater.service

# Disable phoning home for this boot, too
systemctl mask --runtime --now eos-phone-home.{service,timer,path}

# Restart systemd services which mount real storage blocks to the paths under
# /sysroot/ directly. This helps them remount the eos-live overlays in their
# namespace. This is caused by ostree making the /sysroot mount private.
# https://phabricator.endlessm.com/T35625
pattern='$1 ~ "^/dev/" && $2 ~ "^/sysroot/"'
action='{split(FILENAME, p, "/"); print p[3]; nextfile}'
awk "$pattern $action" /proc/*/mounts | uniq | while read -r pid;
do
	service=$(systemctl whoami $pid)
	systemctl restart $service
done
