#!/bin/sh
# Copyright (C) 2016 Endless Mobile, Inc.
# Licensed under the GPLv2
#
# Dumps the 512-byte sectors which make up a file on an NTFS or exFAT
# filesystem.

if [ $# -ne 2 ]; then
  echo "Usage: $0 HOST_DEVICE IMAGE_PATH" >&2
  exit 2
fi

host_device="$1"
image_path="$2"

fstype=$(lsblk --noheadings -o FSTYPE "${host_device}")
if [ $? != 0 ]; then
  echo "$0: failed to detect filesystem type" >&2
  exit 1
fi

case "${fstype}" in
exfat)
  extents=$(dumpexfat -f "${image_path}" "${host_device}")
  ;;
ntfs)
  extents=$(ntfsextents "${host_device}" "${image_path}")
  ;;
*)
  echo "$0: unsupported filesystem ${fstype}" >&2
  exit 1
esac

if [ $? != 0 ]; then
  echo "$0: failed to lookup image on device" >&2
  exit 1
fi

echo "$extents" | while read extent_offset extent_size; do
  [ -z "${extent_offset}" -o -z "${extent_size}" ] && continue
  # Convert bytes to sectors, rounding up
  if [ $(( extent_size % 512 )) != 0 ]; then
    echo "$0: extent size $extent_size not sector-aligned" >&2
    exit 1
  fi
  extent_size=$(( extent_size / 512 ))
  extent_offset=$(( extent_offset / 512 ))
  echo "${extent_offset} ${extent_size}"
done

exit 0
