#!/bin/bash

# Allow xattrs in the user namespace on /run, and by extension in the ostree
# repo, where they are used to record permissions when run as an unprivileged
# user.
mount -o remount,user_xattr /run

# Mount overlays over any directory that might be written to
# Note that /etc was handled in the initramfs since it must be done early.
# The rest of these should be done later, to avoid fighting with ostree-remount
overlay_dirs="bin boot endless home lib opt ostree root sbin srv sysroot/flatpak sysroot/home sysroot/ostree var"
for dir in $overlay_dirs; do
    [ -d /$dir ] || continue
    # If the directory is a symlink, assume it's pointing to a location
    # covered by another top level overlay
    [ -L /$dir ] && continue
    mkdir -p /run/eos-live/$dir /run/eos-live/$dir-workdir
    mount -t overlay -o \
        rw,upperdir=/run/eos-live/$dir,lowerdir=/$dir,workdir=/run/eos-live/$dir-workdir \
        eos-live-$dir /$dir
done

# Disable the updater for this boot
systemctl stop eos-updater.timer
systemctl mask --runtime eos-updater.timer
