#!/bin/bash -e
# Copyright (C) 2017 Endless Mobile, Inc.
# Licensed under the GPLv2

# Sequence these scripts rather than run as separate services
# to avoid races in the flatpak configuration
/usr/sbin/eos-add-flatpak-apps-repos
