#!/bin/bash -e
# Copyright (C) 2015 Endless Mobile, Inc.
# Licensed under the GPLv2

# Detect if we're on Endless hardware with the extra storage disk. If
# so, repartition the disk so that the filesystem can fill the whole
# disk. Then resize the existing filesystem.

# Exit if the stamp file exists. The service file checks for this, but
# also guard against an accidental execution.
stamp_file=/var/eos-extra-resize2
[ -e $stamp_file ] && exit 0

# Identify extra partition device node and parent disk
extra_part=$(readlink -f /dev/disk/by-label/extra)
if [ -z $extra_part ]; then
    echo "repartition: no extra storage found"
    exit 0
fi

case ${extra_part} in
    /dev/mmcblk?p1)
        extra_disk=${extra_part%p1}
        ;;
    /dev/sd?1)
        extra_disk=${extra_part%1}
        ;;
esac

if [ -z "$extra_disk" ]; then
    echo "repartition: no extra disk found for $extra_part"
    exit 0
fi

pt_label=$(blkid -o value -s PTTYPE $extra_disk)

if [ "$pt_label" = "gpt" ]; then
  marker=$(sfdisk --force --part-attrs $extra_disk 1)
else
  marker=$(sfdisk --force --part-type $extra_disk 4)
fi

# Check for our magic "this is Endless" marker to trigger repartitioning.
if [ "$marker" = "GUID:55" ] || [ "$marker" = "dd" ]; then
    # udev might still be busy probing the disk, meaning that it will be
    # in use.
    udevadm settle

    # Figure out the start sector.
    extra_part_name=${extra_part#/dev/}
    part_start=$(< /sys/class/block/$extra_part_name/start)

    # The partition table is recreated below
    echo "Try to resize $extra_part at sector $part_start to fill $extra_disk"
    echo "$part_start" | sfdisk --force --no-reread --label $pt_label $extra_disk

    if [ "$pt_label" = "dos" ]; then
      udevadm settle
      # Remove the marker so that repartitioning does not run again (needed?)
      printf "\x00" | dd of=$extra_disk bs=1 count=1 seek=498 conv=notrunc
    fi
    echo "sfdisk returned $?"
fi

# Force a filesystem check then resize it to fill all available space.
udevadm settle
e2fsck -f -p $extra_part
udevadm settle
resize2fs $extra_part
udevadm settle

# Create the stamp file and exit.
touch $stamp_file
exit 0
