#!/bin/bash -e

# eos-ostree-remotes-config - configure /ostree/repo for safe remote adding
#
# Copyright (C) 2017 Endless Mobile, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.

# Set the repo config option core.add-remotes-config-dir repo option to
# false so that new remotes are not added in /etc/ostree/remotes.d.
# Adding them there is incompatible with the way flatpak modifies
# remotes and will cause the repo to become unusable. Setting that
# option to false ensures that ostree only adds remotes in the repo's
# config file.
#
# This might only needed temporarily until ostree and flatpak get
# updated to do sane remote modification.
#
# https://phabricator.endlessm.com/T19077
# https://github.com/ostreedev/ostree/issues/1134

# Check that /ostree/repo looks like a real repo
[ -d /ostree/repo ] || exit 0
[ -f /ostree/repo/config ] || exit 0
[ -d /ostree/repo/objects ] || exit 0

# Only set the option if it hasn't been set yet
CONFIG_OPT="core.add-remotes-config-dir"
if ! ostree --repo=/ostree/repo config get "$CONFIG_OPT" &>/dev/null; then
    ostree --repo=/ostree/repo config set "$CONFIG_OPT" false
fi
