#!/bin/bash -e
# Copyright (C) 2015 Endless Mobile, Inc.
# Licensed under the GPLv2

# Enable the /var/endless-extra mount for systems upgrading from an
# ostree without the statically enabled unit file.

# There's not a really reliable way to know if this is a multi-disk
# unit, so check if the old SD card resizing stamp file exists. This was
# changed to eos-extra-resize2 prior to 2.6.0, but that was after the
# mounting was reworked so that the mount unit was always enabled.
# Therefore, checking for eos-extra-resize should indicate the old SD
# card mount setup that needs upgrading.
if [ ! -f /var/eos-extra-resize ]; then
    echo "Extra filesystem not resized, assuming single disk image, exiting"
    exit 0
fi

# Previously, an overlayfs was mounted at /endless and statically
# enabled through a symlink to its endless.mount unit. If it's now
# dangling, clean it up.
endless_mount_link=/etc/systemd/system/local-fs.target.wants/endless.mount
if [ -L "$endless_mount_link" ]; then
    endless_mount_unit=$(readlink -f "$endless_mount_link")
    if [ ! -e "$endless_mount_unit" ]; then
        echo "Cleaning up old symlink $endless_mount_link"
        rm -f "$endless_mount_link"
    fi
fi

# Exit if the the wants symlink is already created
wants_dir=/etc/systemd/system/local-fs.target.wants
wants_link="$wants_dir/var-endless\x2dextra.mount"
if [ -e "$wants_link" ]; then
    echo "Mount unit already enabled or masked at $wants_link, exiting"
    exit 0
fi

# Create the wants symlink
mount_unit="var-endless\x2dextra.mount"
mount_unit_path="/etc/systemd/system/$mount_unit"
if [ ! -f "$mount_unit_path" ]; then
    mount_unit_path="/lib/systemd/system/$mount_unit"
fi
echo "Statically enabling mount unit at $wants_link"
mkdir -p "$wants_dir"
ln -sf "$mount_unit_path" "$wants_link"

# Reload systemd so that the new unit is seen to be enabled
systemctl daemon-reload
