#!/bin/bash -e
# Copyright (C) 2018 Endless Mobile, Inc.
# Licensed under the GPLv2

if [ $# -lt 1 -o "$1" -lt 0 -o "$1" -gt 1 ]; then
	echo "Error: 0 or 1 must be specified" >&2
	exit 1
fi

if [ "$1" -eq 0 ]; then
    swapoff /dev/zram0
    echo 1 > /sys/block/zram0/reset
    exit 0
fi

if [ ! -e /sys/block/zram0 ]; then
    modprobe zram
fi

ram_size_kb=$(awk '/MemTotal/{print $2}' /proc/meminfo)
echo $(($ram_size_kb * 2))K > /sys/block/zram0/disksize
mkswap /dev/zram0
swapoff -a
swapon /dev/zram0
