#!/bin/bash -e

# We shipped apps in 3.0.10 and 3.0.11 that have the wrong branch in the
# desktop file. Attempt to fix them.

if [ -d /var/endless-extra/flatpak ]; then
    flatpak_dir=/var/endless-extra/flatpak
else
    flatpak_dir=/var/lib/flatpak
fi

for app_dir in "$flatpak_dir"/app/*; do
    [ -d "$app_dir" ] || continue

    # Figure out what the installed branch is. The current symlink looks
    # like $arch/$branch.
    current=$(readlink "$app_dir"/current)
    current_branch=${current##*/}

    # This only affects eos3 apps
    [ "$current_branch" = eos3 ] || continue

    # Change the --branch=$branch argument in each desktop file and
    # D-Bus service file to use the current branch.
    desktop_dir="$app_dir"/current/active/export/share/applications
    dbus_dir="$app_dir"/current/active/export/share/dbus-1/services
    for exported_file in "$desktop_dir"/*.desktop "$dbus_dir"/*.service; do
        [ -f "$exported_file" ] || continue

        exec_line=$(grep '^Exec' "$exported_file" || true)
        [ -n "$exec_line" ] || continue
        echo "Updating $exported_file to use --branch=$current_branch"
        echo "Before: $exec_line"
        sed -ri "/^Exec/s/(--branch=)[^[:space:]]+/\1${current_branch}/" "$exported_file"
        exec_line=$(grep '^Exec' "$exported_file")
        echo "After:  $exec_line"
    done
done
