#!/bin/bash -e
# Copyright (C) 2015 Endless Mobile, Inc.
# Licensed under the GPLv2

# Enable the /var/endless-extra mount for systems upgrading from an
# ostree without the statically enabled unit file.

# Safely read and match the content of a file.
match_file_content()
{
    local file=$1
    local value=$2
    local content

    [ -f "$file" ] || return 1
    content=$(<"$file") || return $?

    # Return the comparison result
    [ "$content" = "$value" ]
}

# Determine if this is a unit with separate SD card. Currently this is
# the eMMC Sqwerty unit. Need to catch errors and return since this is
# used in a conditional below. Thanks, POSIX.
is_split_unit()
{
    local rootdev

    match_file_content /sys/class/dmi/id/sys_vendor Endless || return $?
    match_file_content /sys/class/dmi/id/product_name EC-200 || return $?
    rootdev=$(findmnt -rvnf -o SOURCE /)
    case "$rootdev" in
	/dev/mmcblk*)
	    return 0
	    ;;
	*)
	    return 1
	    ;;
    esac
}

# Exit if this is not a split unit
if ! is_split_unit; then
    echo "Not split disk unit, exiting"
    exit 0
fi

# Previously, an overlayfs was mounted at /endless and statically
# enabled through a symlink to its endless.mount unit. If it's now
# dangling, clean it up.
endless_mount_link=/etc/systemd/system/local-fs.target.wants/endless.mount
if [ -L "$endless_mount_link" ]; then
    endless_mount_unit=$(readlink -f "$endless_mount_link")
    if [ ! -e "$endless_mount_unit" ]; then
        echo "Cleaning up old symlink $endless_mount_link"
        rm -f "$endless_mount_link"
    fi
fi

# Someone may have installed the single disk image on a unit with the
# extra SD card.
if [ ! -f /var/eos-extra-resize ]; then
    echo "Extra filesystem not resized, assuming single disk image, exiting"
    exit 0
fi

# Exit if the the wants symlink is already created
wants_dir=/etc/systemd/system/local-fs.target.wants
wants_link="$wants_dir/var-endless\x2dextra.mount"
if [ -e "$wants_link" ]; then
    echo "Mount unit already enabled or masked at $wants_link, exiting"
    exit 0
fi

# Create the wants symlink
mount_unit="var-endless\x2dextra.mount"
mount_unit_path="/etc/systemd/system/$mount_unit"
if [ ! -f "$mount_unit_path" ]; then
    mount_unit_path="/lib/systemd/system/$mount_unit"
fi
echo "Statically enabling mount unit at $wants_link"
mkdir -p "$wants_dir"
ln -sf "$mount_unit_path" "$wants_link"

# Reload systemd so that the new unit is seen to be enabled
systemctl daemon-reload

# Start the unit now so that the SD card (hopefully) gets mounted
systemctl start "$mount_unit"
