#!/bin/bash
# Copyright (C) 2016 Endless Mobile, Inc.
# Licensed under the GPLv2
#
# When booting from an image file hosted on a filesystem, this program maps the
# host filesystem to a dm-device with a hole where the image file lives.

for i in $(</proc/cmdline); do
  case $i in
  endless.image.device=*)
    host_device=${i//endless.image.device=}
    ;;
  endless.image.path=*)
    image_path=${i//endless.image.path=}
    ;;
  esac
done

[ -z "${host_device}" -o -z "${image_path}" ] && exit 1

case "${host_device}" in
PARTUUID=*)
  host_device=/dev/disk/by-partuuid/${host_device#PARTUUID=}
  ;;
UUID=*)
  host_device=/dev/disk/by-uuid/${host_device#UUID=}
  ;;
esac

host_device_size=$(blockdev --getsz ${host_device})
if [ $? != 0 ]; then
  echo "Failed to read ${host_device} size"
  exit 1
fi

echo 0 $host_device_size linear $host_device 0 | dmsetup create endless-image-device
if [ $? != 0 ]; then
  echo "Failed to set up a device map for ${host_device}"
  exit 1
fi

exit 0
