#!/bin/bash
shopt -s nullglob

# If no user accounts are available, assume we're still in the factory
# and hence properietary drivers should be erased
homedirs=( /home/* )
if [[ ${#homedirs[@]} == 0 ]]; then
  rm -rf /var/lib/endless-external-drivers/nvidia
fi

exit 0
