#!/bin/sh
# Copyright (C) 2020 Endless OS Foundation LLC
# Licensed under the GPLv2
#
# If a deployment id is found in /run/eos-metrics/deployment-id.txt, this
# script updates the eos-image-version xattr in /sysroot, appending the
# deployment ID to the image version.

file_path="/run/eos-metrics/deployment-id.txt"
deployment_id="$(cat $file_path)"
if [ -z "$deployment_id" ] ; then
  echo "Failed to read $file_path"
  exit 1
fi

eos_image_version="$(attr -q -g eos-image-version /sysroot)"
if [ -z "$eos_image_version" ] ; then
  echo "Failed to read \"eos-image-version\" attribute from /sysroot"
  exit 1
fi

new_eos_image_version="${eos_image_version}_${deployment_id}"
echo "Updating \"eos-image-version\" to \"$new_eos_image_version\""
attr -s eos-image-version -V "$new_eos_image_version" /sysroot
attr_exit_status=$?
if [ $attr_exit_status -ne 0 ] ; then
  echo "Failed to update \"eos-image-version\""
  exit $attr_exit_status
fi
